"""kyoso-agent — Python SDK for the kyoso scene-agent surface.

Wire types live in :mod:`kyoso_agent._generated` (regenerated from
the Rust JSON Schema via ``scripts/codegen.sh``); the client and
transport machinery is hand-written here.
"""

from . import _generated
from ._generated import (
    Catalog,
    Change,
    ChangeKind,
    CreateSpec,
    Cursor,
    EdgePattern,
    EdgeRef,
    EntityReport,
    Frame,
    FrameData,
    GradientStop,
    GradientType,
    ImageScaleMode,
    LayoutMode,
    MatchRefs,
    MoveSpec,
    MutateError,
    MutateResult,
    NavDir,
    NavEdgeFilter,
    NavOpts,
    NewNode,
    Node,
    NodeKind,
    NodePattern,
    NodeRef,
    NodeTarget,
    OrderKey,
    OutlineNode,
    Paint,
    PatternAnchor,
    PatternDirection,
    PatternSpec,
    QueryResult,
    QuerySpec,
    Rectangle,
    RectangleData,
    ScanOpts,
    SceneIndex,
    ScenePath,
    SessionId,
    Size,
    SubtreeCost,
    Text,
    TextData,
    TransformPatch,
    TypeStyle,
    UpdatePatch,
    Walk,
    WalkOpts,
    WalkRow,
    WalkStrategy,
    WatchOpts,
    WatchPage,
)
from .client import SceneAgent
from .transport import MockTransport, PyO3Transport, Transport, TransportError

__all__ = [
    # Client + transport
    "SceneAgent",
    "Transport",
    "TransportError",
    "MockTransport",
    "PyO3Transport",
    # Wire types
    "Catalog",
    "Change",
    "ChangeKind",
    "CreateSpec",
    "Cursor",
    "EdgePattern",
    "EdgeRef",
    "EntityReport",
    "Frame",
    "FrameData",
    "GradientStop",
    "GradientType",
    "ImageScaleMode",
    "LayoutMode",
    "MatchRefs",
    "MoveSpec",
    "MutateError",
    "MutateResult",
    "NavDir",
    "NavEdgeFilter",
    "NavOpts",
    "NewNode",
    "Node",
    "NodeKind",
    "NodePattern",
    "NodeRef",
    "NodeTarget",
    "OrderKey",
    "OutlineNode",
    "Paint",
    "PatternAnchor",
    "PatternDirection",
    "PatternSpec",
    "QueryResult",
    "QuerySpec",
    "Rectangle",
    "RectangleData",
    "ScanOpts",
    "SceneIndex",
    "ScenePath",
    "SessionId",
    "Size",
    "SubtreeCost",
    "Text",
    "TextData",
    "TransformPatch",
    "TypeStyle",
    "UpdatePatch",
    "Walk",
    "WalkOpts",
    "WalkRow",
    "WalkStrategy",
    "WatchOpts",
    "WatchPage",
    "_generated",
]
