# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-05-26T23:09:10+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class KyosoAgent(RootModel[Any]):
    root: Any = Field(..., title="kyoso_agent")
    """
    Wire surface for the kyoso_agent SceneRead / SceneMutate verbs.
    """


class KindCounts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    frame: int | None = Field(None, ge=0)
    rectangle: int | None = Field(None, ge=0)
    text: int | None = Field(None, ge=0)


class Catalog(BaseModel):
    kind_counts: KindCounts
    max_depth: int = Field(..., ge=0)
    total_nodes: int = Field(..., ge=0)


class ChangeKind(Enum):
    added = "Added"
    removed = "Removed"
    modified = "Modified"
    moved = "Moved"


class CrdtId(BaseModel):
    """
    Stable global identifier for an element (node, edge, comment, …) or
    for an individual operation.

    Two-tuple of `(peer, seq)` where `seq` is the peer's local counter.
    Once minted on a peer, this ID is permanent and shared across all
    replicas. The encoding is varint-friendly (small peer IDs and dense
    counters compress well under postcard).
    """

    peer: int = Field(..., ge=0)
    seq: int = Field(..., ge=0)


class GradientStop(BaseModel):
    color: list[float] = Field(..., max_length=4, min_length=4)
    position: float
    """
    `[0.0, 1.0]` along the gradient.
    """


class GradientType(Enum):
    linear = "Linear"
    radial = "Radial"
    angular = "Angular"
    diamond = "Diamond"


class ImageScaleMode(Enum):
    fill = "Fill"
    fit = "Fit"
    tile = "Tile"
    stretch = "Stretch"


class LayoutMode(Enum):
    none = "none"
    horizontal = "horizontal"
    vertical = "vertical"


class NavDir(Enum):
    out = "Out"
    """
    Outgoing edges only — successors I point to.
    """
    in_ = "In"
    """
    Incoming edges only — predecessors pointing to me.
    """
    both = "Both"
    """
    Union of Out and In at each hop. Undirected neighborhood.
    """
    downstream = "Downstream"
    """
    Transitive closure of `Out`. Ignores `depth_limit` (uses
    `GraphQuery::downstream_nodes`).
    """
    upstream = "Upstream"
    """
    Transitive closure of `In`. Ignores `depth_limit`.
    """
    component = "Component"
    """
    Whole connected component (undirected). Ignores `depth_limit`.
    """


class NavEdgeFilter(Enum):
    all = "All"
    """
    Tree (ChildOf) + entity-edges (SceneEdge). Default.
    """
    tree_only = "TreeOnly"
    """
    Only the tree hierarchy. For walking a subtree manually one
    hop at a time. (`walk` is usually better for whole subtrees.)
    """
    entity_edges_only = "EntityEdgesOnly"
    """
    Only the entity-edge graph — the "weave" relations that don't
    live in the parent-child hierarchy. This is where most
    agent-relevant graph crawls happen.
    """


class NodeKind(Enum):
    """
    Discriminator tag: which variant of [`Node`](crate::node::Node) does
    this entity carry? Inserted atomically with the variant's data via
    the `*Data` bundles (see [`FrameData`](crate::FrameData) etc.)
    so the tag and the data cannot drift apart.
    """

    frame = "frame"
    rectangle = "rectangle"
    text = "text"


class NodePattern(BaseModel):
    """
    Filters that apply to a single pattern node slot. Applied as a
    post-match step — matches survive only if every bound node passes.
    """

    kind: NodeKind | None = None
    name: str | None = None
    """
    Match against Frame's `name` or Text's `content`. Other variants
    always fail this filter.
    """


class NodeTarget1(RootModel[int]):
    root: int = Field(..., ge=0)
    """
    Input form for tool methods: a raw `Entity` (fast in-process) or a
    [`NodeRef`] (durable). Both are resolved via [`NodeTarget::resolve`].

    Most `SceneAgent` methods take `impl Into<NodeTarget>` so callers
    can pass whichever they have. Returned rows always carry `NodeRef`
    — so a typical loop is `entity_returned_from_query → next call`,
    with no manual conversion.

    Wire form: serialized as the inner `NodeRef` (with `entity:` and
    `session:` cache hints when present). The `Entity`-only variant
    serializes as `{"entity": <bits>}` — only meaningful in-process,
    which is acceptable since cross-process callers always have a
    `NodeRef`.
    """


class OrderKey(RootModel[str]):
    root: str
    """
    Per-child fractional ordering key.

    Strings sort lexicographically over a printable-ASCII alphabet, so
    inserting between two existing siblings is always possible without
    renumbering anyone else. See [`OrderKey::between`] for the midpoint
    generator.
    """


class Solid(BaseModel):
    color: list[float] = Field(..., max_length=4, min_length=4)
    """
    sRGB linear with alpha, in `[0.0, 1.0]`.
    """


class Paint1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    solid: Solid = Field(..., alias="Solid")


class Gradient(BaseModel):
    kind: GradientType
    stops: list[GradientStop]


class Paint2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    gradient: Gradient = Field(..., alias="Gradient")


class Image(BaseModel):
    image_ref: str
    """
    Server-resolved image key. The actual image bytes are
    fetched separately (out of the document's CRDT scope).
    """
    scale_mode: ImageScaleMode


class Paint3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    image: Image = Field(..., alias="Image")


class Paint(RootModel[Paint1 | Paint2 | Paint3]):
    root: Paint1 | Paint2 | Paint3


class PatternDirection(Enum):
    forward = "Forward"
    """
    Match a graph edge `bound(from) → bound(to)`.
    """
    backward = "Backward"
    """
    Match a graph edge `bound(to) → bound(from)` (pattern arrow
    points opposite to the actual edge).
    """


class Rectangle(BaseModel):
    corner_radius: float
    fills: list[Paint]
    stroke_weight: float
    strokes: list[Paint]


class ScenePath(RootModel[str]):
    root: str


class SessionId(RootModel[UUID]):
    root: UUID
    """
    Identifies one run of the scene agent. New UUID per `SceneAgent::new()`.

    Equivalent to Rerun's `RecordingId`. An `ApplicationId` analogue (a
    stable schema name across runs) can be layered on later if multiple
    kyoso apps need to coexist in one agent — for now, single UUID is
    enough to detect "this `NodeRef` is from a previous process."
    """


class Size(BaseModel):
    height: float
    width: float


class SubtreeCost(BaseModel):
    """
    Serializable mirror of [`kyoso_graph::cost::Cost`] so the SDK doesn't
    require pulling the graph crate just to read an index. Same fields.
    """

    estimated_items: int = Field(..., ge=0)
    estimated_work: int = Field(..., ge=0)


class TransformPatch(BaseModel):
    """
    Wire-friendly mirror of Bevy's `Transform`. Translation as `[x, y, z]`,
    rotation as `[x, y, z, w]` (quaternion), uniform/non-uniform scale as
    `[x, y, z]`. Round-trips through `From<Transform>` / `Into<Transform>`.
    """

    rotation: list[float] = Field(..., max_length=4, min_length=4)
    scale: list[float] = Field(..., max_length=3, min_length=3)
    translation: list[float] = Field(..., max_length=3, min_length=3)


class TypeStyle(BaseModel):
    font_family: str
    font_size: float
    font_weight: int = Field(..., ge=0)
    line_height: float


class UpdatePatch(BaseModel):
    """
    Partial update. All fields optional — the builder methods are the
    expected entry point. Variant-specific fields no-op silently on
    non-matching variants today; we'll surface that as a typed error
    once we have a stronger reason to (see [`MutateError::VariantMismatch`]).
    """

    frame_name: str | None = None
    """
    Rename a Frame. No-op on non-Frame entities.
    """
    text_content: str | None = None
    """
    Set Text content. No-op on non-Text entities.
    """
    transform: TransformPatch | None = None
    """
    Replace the entity's [`Transform`] wholesale (works on any
    variant — every scene entity carries one). On the wire we use
    [`TransformPatch`] because Bevy's `Transform` doesn't carry
    `Serialize`/`Deserialize` in the workspace's `default-features = false`
    build.
    """


class WalkStrategy(Enum):
    dfs = "Dfs"
    bfs = "Bfs"


class Cursor(BaseModel):
    """
    Position in the event stream for `watch(since)`.

    Hybrid model:
    - `generation` — session-local counter bumped on every relevant ECS
      change. Covers derived/read-only state too.
    - `last_replicated_op` — opaque monotonic identifier from the sync
      engine, present when the change came through CRDT replication.
      Lets the agent reason about cross-process ordering with the human
      operator's edits.

    `session` lets the SDK return `buffer_overflow: true` cleanly when a
    cursor from a prior session is presented — the agent re-scans rather
    than receiving stale-but-plausible deltas.
    """

    generation: int = Field(..., ge=0)
    last_replicated_op: int | None = Field(None, ge=0)
    session: SessionId


class EdgePattern(BaseModel):
    direction: PatternDirection | None = "Forward"
    from_: int = Field(..., alias="from", ge=0)
    to: int = Field(..., ge=0)


class Frame(BaseModel):
    clips_content: bool
    """
    Whether children are clipped to the frame's bounds.
    Figma `Frame` ⇒ `true`; Figma `Group` ⇒ `false`.
    """
    fills: list[Paint]
    """
    Whole-list LWW. Concurrent fill edits on different peers will
    not compose — last writer wins on the entire list. See
    `paint.rs` for the rationale.
    """
    layout_mode: LayoutMode
    name: str
    stroke_weight: float
    strokes: list[Paint]


class FrameData(BaseModel):
    """
    Owned Frame variant payload + Bevy `Bundle`. Spawn-side mirror of
    [`FrameQueryData`].

    The `#[require(NodeKind = NodeKind::Frame)]` on [`Frame`] auto-inserts
    the discriminator, so the sync layer's per-component ops produce the
    same archetype as the local `*Data` spawn path.
    """

    frame: Frame
    size: Size


class VariantMismatch(BaseModel):
    expected: NodeKind
    patched: str


class MutateError1(BaseModel):
    """
    An `UpdatePatch` field doesn't apply to this entity's variant.
    E.g. `frame_name` on a Text node. Today we silently no-op for
    such fields; this variant is reserved for the future "strict"
    mode.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    variant_mismatch: VariantMismatch = Field(..., alias="VariantMismatch")


class MutateError(
    RootModel[
        Literal["TargetNotFound"]
        | Literal["ParentNotFound"]
        | MutateError1
        | Literal["EmptyPatch"]
    ]
):
    root: (
        Literal["TargetNotFound"]
        | Literal["ParentNotFound"]
        | MutateError1
        | Literal["EmptyPatch"]
    )


class NavOpts(BaseModel):
    depth_limit: int | None = Field(None, ge=0)
    """
    Hop depth. `None` defaults to 1 (immediate neighbors only).
    Ignored for `Downstream` / `Upstream` / `Component`.
    """
    direction: NavDir | None = "Out"
    edges: NavEdgeFilter | None = "All"
    kinds: list[NodeKind] | None = []
    """
    Filter result rows by kind. Empty = all kinds.
    """
    max_items: int | None = Field(0, ge=0)
    """
    Cap on row count. 0 = unlimited.
    """


class NewNode1(BaseModel):
    """
    Owned Frame variant payload + Bevy `Bundle`. Spawn-side mirror of
    [`FrameQueryData`].

    The `#[require(NodeKind = NodeKind::Frame)]` on [`Frame`] auto-inserts
    the discriminator, so the sync layer's per-component ops produce the
    same archetype as the local `*Data` spawn path.
    """

    frame: Frame
    size: Size
    kind: Literal["frame"]


class NewNode2(BaseModel):
    """
    Owned Rectangle variant payload + Bevy `Bundle`.
    """

    rectangle: Rectangle
    size: Size
    kind: Literal["rectangle"]


class Node1(BaseModel):
    """
    Owned Frame variant payload + Bevy `Bundle`. Spawn-side mirror of
    [`FrameQueryData`].

    The `#[require(NodeKind = NodeKind::Frame)]` on [`Frame`] auto-inserts
    the discriminator, so the sync layer's per-component ops produce the
    same archetype as the local `*Data` spawn path.
    """

    frame: Frame
    size: Size
    kind: Literal["frame"]


class Node2(BaseModel):
    """
    Owned Rectangle variant payload + Bevy `Bundle`.
    """

    rectangle: Rectangle
    size: Size
    kind: Literal["rectangle"]


class NodeRef(BaseModel):
    """
    Agent-facing reference to a scene node — what tools return and accept.

    `path` is canonical; the other fields are cache hints. Resolver
    strategy (see [`NodeRef::resolve`]):

    1. `entity` if `session` matches the current session and the entity
       still exists in the world.
    2. `crdt_id` via [`EntityCrdtIndex::entity_for_node`].
    3. Walk the `path` from root.
    """

    crdt_id: CrdtId | None = None
    """
    Set for replicated nodes. Durable across reruns (it's the CRDT
    site identity), so this is the preferred fast path after `path`.
    """
    entity: int | None = Field(None, ge=0)
    """
    Per-session cache. `Entity` is encoded via `Entity::to_bits()`
    for serde compat. Honoured only when `session` matches.
    """
    path: ScenePath
    session: SessionId | None = None
    """
    Session this `entity` cache belongs to.
    """


class NodeTarget(RootModel[NodeRef | NodeTarget1]):
    root: NodeRef | NodeTarget1
    """
    Input form for tool methods: a raw `Entity` (fast in-process) or a
    [`NodeRef`] (durable). Both are resolved via [`NodeTarget::resolve`].

    Most `SceneAgent` methods take `impl Into<NodeTarget>` so callers
    can pass whichever they have. Returned rows always carry `NodeRef`
    — so a typical loop is `entity_returned_from_query → next call`,
    with no manual conversion.

    Wire form: serialized as the inner `NodeRef` (with `entity:` and
    `session:` cache hints when present). The `Entity`-only variant
    serializes as `{"entity": <bits>}` — only meaningful in-process,
    which is acceptable since cross-process callers always have a
    `NodeRef`.
    """


class OutlineNode(BaseModel):
    """
    One row in the outline forest. `children` is the recursive structure;
    `elided_children` tells the agent how many descendants the outline
    hid (either because of `depth` or `max_outline_rows`).
    """

    child_count: int = Field(..., ge=0)
    children: list[OutlineNode]
    depth: int = Field(..., ge=0)
    elided_children: int = Field(..., ge=0)
    kind: NodeKind | None = None
    name: str | None = None
    node: NodeRef
    subtree_cost: SubtreeCost


class PatternAnchor(BaseModel):
    """
    Pin a specific pattern node slot to a known scene entity.
    Anchored matches start search from this binding.
    """

    pattern_node: int = Field(..., ge=0)
    target: NodeTarget


class PatternSpec(BaseModel):
    """
    Declarative description of a subgraph pattern to match.

    Crosses the FFI / MCP wire without lifetimes. Indices into `nodes`
    and `edges` form the slot space — i.e. `MatchRefs.nodes[i]` is the
    binding of `spec.nodes[i]`.
    """

    anchors: list[PatternAnchor] | None = None
    edges: list[EdgePattern] | None = Field([], validate_default=True)
    nodes: list[NodePattern] | None = Field([], validate_default=True)


class QueryResult(BaseModel):
    rows: list[NodeRef]
    """
    Matched nodes in `NodeRef` space. For non-`SceneNode` entities
    (e.g. edges, internal infrastructure), the `path` is empty (root).
    """
    truncated: bool
    """
    `max_items` truncated the result before all candidates were
    considered. Issue another query with a higher cap or narrower
    filter.
    """
    unknown_components: list[str]
    """
    Component-type names from the spec that the registry didn't
    recognise. The query still ran with the remaining names — this
    field lets the agent detect typos / unregistered types instead
    of silently matching everything.
    """


class QuerySpec(BaseModel):
    """
    Filter spec. `with`/`without` are component-type-name strings;
    `under` confines the search to a subtree; `max_items` caps the
    result.
    """

    max_items: int | None = Field(0, ge=0)
    """
    Cap on result rows. `0` = unlimited.
    """
    under: NodeRef | None = None
    """
    Restrict the search to the subtree rooted at this node
    (inclusive). `None` = entire world.
    """
    with_: list[str] | None = Field([], alias="with")
    """
    Entities must carry **every** listed component.
    """
    without: list[str] | None = None
    """
    Entities must carry **none** of the listed components.
    """


class RectangleData(BaseModel):
    """
    Owned Rectangle variant payload + Bevy `Bundle`.
    """

    rectangle: Rectangle
    size: Size


class ScanOpts(BaseModel):
    """
    Knobs for [`SceneAgent::scan`](crate::SceneAgent::scan). All optional;
    sane defaults keep the result small enough for a first call from an
    agent that knows nothing about the scene yet.
    """

    depth: int | None = Field(2, ge=0)
    """
    How deep to descend the outline. Default 2 — enough to see "what
    pages exist" and "what's at the top level of each page" without
    flooding the agent. `0` = catalog-only.
    """
    kinds: list[NodeKind] | None = []
    """
    Filter outline rows by kind. Empty = all kinds.
    """
    max_outline_rows: int | None = Field(256, ge=0)
    """
    Cap on total outline rows. When exceeded, deeper / later
    children are dropped and `OutlineNode::elided_children` is
    incremented on the parent.
    """
    under: NodeRef | None = None
    """
    Confine the outline to the subtree rooted at this node. `None` =
    scene roots.
    """


class SceneIndex(BaseModel):
    catalog: Catalog
    generation: int = Field(..., ge=0)
    roots: list[OutlineNode]
    session: SessionId


class Text(BaseModel):
    content: str
    fills: list[Paint]
    style: TypeStyle


class TextData(BaseModel):
    """
    Owned Text variant payload + Bevy `Bundle`.
    """

    size: Size
    text: Text


class WalkOpts(BaseModel):
    depth_limit: int | None = Field(None, ge=0)
    """
    Cap depth (in tree edges from root). `None` = unbounded.
    """
    kinds: list[NodeKind] | None = []
    """
    Filter result rows by kind. Empty = all kinds.
    (Filter is post-yield — see `TraversalQuery` semantics.)
    """
    max_items: int | None = Field(0, ge=0)
    """
    Cap on row count. 0 = unlimited.
    """
    strategy: WalkStrategy | None = "Dfs"


class WalkRow(BaseModel):
    depth: int = Field(..., ge=0)
    kind: NodeKind | None = None
    node: NodeRef


class WatchOpts(BaseModel):
    events: list[ChangeKind] | None = []
    """
    Filter to specific change kinds. Empty = no filter.
    """
    kinds: list[NodeKind] | None = []
    """
    Filter to specific kinds. Empty = no filter.
    """
    max_items: int | None = Field(0, ge=0)
    """
    Cap on rows in the returned page. 0 = unlimited.
    """
    under: NodeRef | None = None
    """
    Confine to changes whose `entity` resolves under this subtree.
    `None` = whole scene.
    """


class Change(BaseModel):
    """
    One row in the [`WatchPage`] result. `node` carries the path + cache
    hints; `kind` is the coalesced kind; `change_count` is how many raw
    events were folded into this row.
    """

    change_count: int = Field(..., ge=0)
    generation: int = Field(..., ge=0)
    kind: ChangeKind
    node: NodeRef
    node_kind: NodeKind | None = None
    """
    Best-effort `NodeKind` — present when the entity still exists
    at drain time. `None` for `Removed` and for any node the
    resolver can't classify.
    """


class EdgeRef(BaseModel):
    """
    Agent-facing reference to an edge entity. Edges don't sit in the
    tree, so they don't have a `ScenePath` — they're identified by the
    `(from, to)` NodeRef pair plus the entity bits.
    """

    entity: int | None = Field(None, ge=0)
    from_: NodeRef = Field(..., alias="from")
    to: NodeRef


class MatchRefs(BaseModel):
    """
    NodeRef-shaped projection of a [`Match`] returned by
    [`SceneAgent::match_refs`]. Indices match `PNode.0` / `PEdge.0` so
    the [`pattern_builder()`](SceneAgent::pattern_builder)-issued
    handles stay valid as lookups.
    """

    edges: list[EdgeRef]
    nodes: list[NodeRef]


class MoveSpec(BaseModel):
    """
    Move (reparent / reorder) a node. `new_parent: None` promotes to
    scene root.
    """

    new_parent: NodeTarget | None = None
    position: OrderKey
    target: NodeTarget


class MutateResult(BaseModel):
    """
    Returned from every mutation. `node` is the post-mutation [`NodeRef`]
    for the affected entity (for [`delete`], it's the *pre-mutation*
    ref since the entity no longer exists). `cursor` is the full
    post-mutation [`Cursor`] — pass it directly to
    [`crate::SceneRead::watch`] to observe everything *after* this
    mutation lands.
    """

    cursor: Cursor
    node: NodeRef


class NewNode3(BaseModel):
    """
    Owned Text variant payload + Bevy `Bundle`.
    """

    size: Size
    text: Text
    kind: Literal["text"]


class NewNode(RootModel[NewNode1 | NewNode2 | NewNode3]):
    root: NewNode1 | NewNode2 | NewNode3
    """
    The variant data for a new node. Mirrors the variant set in
    [`kyoso_core::Node`] but is *write-shaped* — it carries the full
    bundle the entity will be spawned with.
    """


class Node3(BaseModel):
    """
    Owned Text variant payload + Bevy `Bundle`.
    """

    size: Size
    text: Text
    kind: Literal["text"]


class Node(RootModel[Node1 | Node2 | Node3]):
    root: Node1 | Node2 | Node3
    """
    The public node taxonomy. Serializes with an internal `"kind"` tag
    (`"frame"` / `"rectangle"` / `"text"`) for AI / RPC consumers.

    Spawn into the ECS via [`Node::spawn`]. Materialize back via
    [`SceneWorld::read_as`](crate::SceneWorld::read_as) (single-entity)
    or [`SceneWorld::traverse_typed::<SceneNode>`](crate::SceneWorld::traverse_typed)
    (walking) — both go through the
    [`kyoso_graph::variant::NodeVariants`] tuple dispatch.
    """


class Walk(BaseModel):
    cost: SubtreeCost
    root: NodeRef
    rows: list[WalkRow]
    truncated: bool
    """
    True when `max_items` truncated the result before all matching
    rows were collected. The agent can issue another `walk` rooted
    at the last yielded row to continue.
    """


class WatchPage(BaseModel):
    buffer_overflow: bool
    """
    Ring buffer evicted before the agent read. The agent's
    incremental view is gone; the recovery path is `scan()` →
    rebuild the mental model.
    """
    changes: list[Change]
    has_more: bool
    """
    More changes exist past `max_items` — issue another `watch`
    with `next_cursor` to get them. Today's draft drains in one
    pass so this is always false; left in the type so the wire
    shape doesn't need a future change.
    """
    next_cursor: Cursor


class CreateSpec(BaseModel):
    """
    What to create + where to put it. `parent: None` makes a scene
    root; `position: None` defaults to `OrderKey("a")` when a parent
    is set (deterministic placement).
    """

    data: NewNode
    parent: NodeTarget | None = None
    position: OrderKey | None = None


class EntityReport(BaseModel):
    """
    What [`SceneAgent::inspect`] returns: the resolved [`NodeRef`],
    the typed sum-type [`Node`] materialisation (if it matches a known
    variant), and the schemaless component-name dump.

    `entity_bits` is the live `Entity::to_bits()` at the moment of the
    call — only meaningful when paired with this run's [`SessionId`].
    Cross-process callers should ignore it and route work through
    `node` ([`NodeRef`]).
    """

    component_names: list[str]
    entity_bits: int | None = Field(None, ge=0)
    """
    Per-session opaque entity handle — `Entity::to_bits()`. `None`
    if the target couldn't be resolved.
    """
    node: NodeRef
    variant: Node | None = None
    """
    Typed `Node` materialisation, when the entity carries a known
    kind. `None` for entities with no matching variant.
    """


OutlineNode.model_rebuild()
