//! Typed-schema sync path for graph-model components.
//!
//! For each Bevy component `C` that implements [`SchemaSync`]:
//!
//! - A [`SchemaDoc<C::Schema>`] resource wraps a
//!   [`GraphBackend<C::Schema>`] holding the typed CRDT state for
//!   every node that carries `C`. Schema state is updated *only* by
//!   server-confirmed ops via [`GraphBackend::apply_property_op`].
//! - **Outbound**: `detect_typed_changes::<C>` runs whenever
//!   `Changed<C>` fires. It compares the Bevy component's current
//!   value against the document's known state via
//!   [`SchemaSync::changes_against`] and emits one wire op per changed
//!   field through the shared [`crate::ClientSyncEngine`].
//! - **Inbound**: `route_typed_inbound::<C>` reads the
//!   [`crate::RemoteOpApplied`] event stream, filters for ops whose
//!   `Path` head matches `C::SCHEMA_NAME`, strips that prefix, and
//!   routes the op to [`GraphBackend::apply_property_op`].
//! - **Projection**: `project_typed_to_bevy::<C>` watches the document
//!   for changes and writes the schema state back to the matching Bevy
//!   component via [`SchemaSync::write_back`].
//!
//! ## Wire-format namespacing
//!
//! `Path` is shared across all schemas, so each typed schema prefixes
//! its field paths with [`SchemaSync::SCHEMA_NAME`]:
//!
//! ```text
//! Set GraphNode.radius = 5.0  →  path = ["GraphNode", "radius"]
//! Set GraphEdge.line_width = 2  →  path = ["GraphEdge", "line_width"]
//! ```
//!
//! Inbound dispatch matches the head segment; the schema's own
//! `SchemaApply` impl (generated by `derive(Crdt)`) consumes the rest.

use std::collections::HashMap;
use std::marker::PhantomData;
use std::ops::{Deref, DerefMut};

use bevy::ecs::component::Mutable;
use bevy::prelude::*;
use kyoso_crdt::{
    Backend, Crdt, CrdtId, IntoWireOp, Op, OpaqueValue, Path, PathSegment, SchemaApply, WireDelta,
};
use kyoso_graph_crdt::{GraphTopology, OpKind};

use crate::engine::ClientSyncEngine;
use crate::index::EntityCrdtIndex;
use crate::plugin::{RemoteOpApplied, Syncable};

/// Bevy [`Resource`] wrapper around a schema-only [`Backend`].
///
/// Holds per-id typed schema state for one component type. Backed by
/// the generic [`Backend`] so `schema(id)` / `ensure_schema(id)` access
/// the schemas map directly without gating on topology liveness — the
/// topology lives in the structural [`ClientSyncEngine`], not here.
#[derive(Resource)]
pub struct SchemaDoc<S>(pub Backend<GraphTopology, S>)
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static;

impl<S> Default for SchemaDoc<S>
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static,
{
    fn default() -> Self {
        Self(Backend::default())
    }
}

impl<S> Deref for SchemaDoc<S>
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static,
{
    type Target = Backend<GraphTopology, S>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<S> DerefMut for SchemaDoc<S>
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static,
{
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

/// Bridge between a Bevy component and a `derive(Crdt)` schema struct.
///
/// `PartialEq` on `Schema` is required so `detect_typed_changes` can
/// distinguish "the doc holds real hydrated state" from "the doc is
/// still at its empty/default lattice bottom" — the discriminator that
/// suppresses spurious "reset to default" ops on reconnect.
pub trait SchemaSync:
    Component<Mutability = Mutable> + Default + Sized + Send + Sync + 'static
{
    type Schema: Crdt + SchemaApply + Default + Clone + PartialEq + Send + Sync + 'static;
    const SCHEMA_NAME: &'static str;
    fn changes_against(&self, current: &Self::Schema) -> Vec<<Self::Schema as Crdt>::Mutation>;
    fn write_back(&mut self, schema: &Self::Schema);
}

/// Bridge for `#[crdt(with = "Type")]` schema fields — the escape hatch
/// for component fields whose Bevy type doesn't satisfy the standard
/// schema bounds (`Handle<Image>`, `Entity` references, opaque tokens
/// from external systems, types with custom serialization).
pub trait SchemaField: Crdt {
    type Component;
    fn changes_against(&self, component: &Self::Component) -> Vec<<Self as Crdt>::Mutation>;
    fn project_to(&self, component: &mut Self::Component);
}

impl<T> SchemaField for kyoso_crdt::types::LwwRegister<T>
where
    T: Clone
        + PartialEq
        + Default
        + serde::Serialize
        + for<'de> serde::Deserialize<'de>
        + Send
        + Sync
        + 'static,
{
    type Component = T;

    fn changes_against(&self, component: &Self::Component) -> Vec<<Self as Crdt>::Mutation> {
        let baseline = T::default();
        if self.get().unwrap_or(&baseline) != component {
            vec![kyoso_crdt::types::LwwMut::Set(component.clone())]
        } else {
            Vec::new()
        }
    }

    fn project_to(&self, component: &mut Self::Component) {
        if let Some(value) = self.get() {
            *component = value.clone();
        }
    }
}

// ---------------------------------------------------------------------------
// SchemaTarget — abstracts node vs edge for the typed-schema pipeline.
//
// Both directions of the pipeline (detect Bevy → wire op, route wire op →
// schema state) differ only in: which side of [`EntityCrdtIndex`] to
// consult, which [`OpKind`] variant to emit/match, and which `*_of_entity`
// map to iterate during projection. Capturing those four bits behind a
// trait lets one set of systems serve both nodes and edges.
// ---------------------------------------------------------------------------

/// Runtime discriminant for [`SchemaTarget`]. Used by
/// [`SchemaHydrators`] to key per-target-kind hydrators.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum TargetKind {
    Node,
    Edge,
}

/// Whether a typed schema attaches to node IDs or reference-edge IDs.
pub trait SchemaTarget: 'static + Send + Sync {
    /// Runtime discriminant. Lets hydrator lookups disambiguate when
    /// the same `SCHEMA_NAME` could in principle attach to either side.
    const KIND: TargetKind;

    /// Look up the `CrdtId` bound to `entity` for this target kind.
    fn id_for(index: &EntityCrdtIndex, entity: Entity) -> Option<CrdtId>;

    /// All `(entity, id)` pairs for this target kind. Used by projection
    /// to iterate every replicated entity that might need a write-back.
    fn pairs(index: &EntityCrdtIndex) -> &HashMap<Entity, CrdtId>;

    /// Build the outbound [`OpKind`] for a property mutation on this target.
    fn build_op(target: CrdtId, path: Path, delta: WireDelta) -> OpKind;

    /// Match a received [`OpKind`]; return `(target, path, delta)` iff it's
    /// a property op for this target kind.
    fn match_inbound(op: &OpKind) -> Option<(CrdtId, &Path, &WireDelta)>;
}

/// Marker: schema attaches to graph nodes.
pub struct NodeTarget;
impl SchemaTarget for NodeTarget {
    const KIND: TargetKind = TargetKind::Node;
    fn id_for(index: &EntityCrdtIndex, entity: Entity) -> Option<CrdtId> {
        index.node_id(entity)
    }
    fn pairs(index: &EntityCrdtIndex) -> &HashMap<Entity, CrdtId> {
        &index.node_of_entity
    }
    fn build_op(target: CrdtId, path: Path, delta: WireDelta) -> OpKind {
        OpKind::SetNodeProperty { target, path, delta }
    }
    fn match_inbound(op: &OpKind) -> Option<(CrdtId, &Path, &WireDelta)> {
        if let OpKind::SetNodeProperty { target, path, delta } = op {
            Some((*target, path, delta))
        } else {
            None
        }
    }
}

/// Marker: schema attaches to reference edges.
pub struct EdgeTarget;
impl SchemaTarget for EdgeTarget {
    const KIND: TargetKind = TargetKind::Edge;
    fn id_for(index: &EntityCrdtIndex, entity: Entity) -> Option<CrdtId> {
        index.edge_id(entity)
    }
    fn pairs(index: &EntityCrdtIndex) -> &HashMap<Entity, CrdtId> {
        &index.edge_of_entity
    }
    fn build_op(target: CrdtId, path: Path, delta: WireDelta) -> OpKind {
        OpKind::SetRefEdgeProperty { target, path, delta }
    }
    fn match_inbound(op: &OpKind) -> Option<(CrdtId, &Path, &WireDelta)> {
        if let OpKind::SetRefEdgeProperty { target, path, delta } = op {
            Some((*target, path, delta))
        } else {
            None
        }
    }
}

// ---------------------------------------------------------------------------
// SchemaHydrators — registry for snapshot-driven typed-schema installation.
//
// When the Welcome handler decodes a server snapshot, each
// `OpaqueRecord` entry needs to be routed into the matching
// `SchemaDoc<C::Schema>` Bevy resource. The right `C` is identified by
// (target kind, schema name); the registry maps that pair to a
// monomorphized hydrator that knows how to install the opaque state
// into the typed schema doc.
// ---------------------------------------------------------------------------

/// Signature of one hydrator. Takes the world (for resource access),
/// the entity ID the state belongs to, the schema-relative path inside
/// the schema struct, and the opaque per-primitive state to install.
pub type HydratorFn = fn(&mut World, target: CrdtId, path: Path, field: OpaqueValue);

/// Registry of per-(target-kind, schema-name) hydrators.
///
/// Populated at plugin-build time by
/// [`SchemaSyncedNodeComponentPlugin`] and
/// [`SchemaSyncedEdgeComponentPlugin`]. Consulted at Welcome time by
/// the [`crate::plugin::graph_inbound_system`] when a snapshot arrives.
#[derive(Resource, Default)]
pub struct SchemaHydrators {
    /// (target-kind, schema-name) → hydrator. `String` key (not
    /// `&'static str`) so lookups can use owned strings extracted from
    /// snapshot paths without lifetime gymnastics.
    pub(crate) by_key: HashMap<(TargetKind, String), HydratorFn>,
}

impl SchemaHydrators {
    /// Register the hydrator for component `C` under `T`'s kind. Called
    /// once per `SchemaSynced*ComponentPlugin` at app build time.
    pub fn register<T, C>(&mut self)
    where
        T: SchemaTarget,
        C: SchemaSync,
        <C::Schema as Crdt>::Delta: IntoWireOp,
        <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
    {
        self.by_key.insert(
            (T::KIND, C::SCHEMA_NAME.to_string()),
            hydrate_schema_doc::<C> as HydratorFn,
        );
    }
}

/// Hydrator monomorphized for component `C`. Looks up the matching
/// [`SchemaDoc<C::Schema>`] resource and installs `field` at `path`.
///
/// `ensure_schema` is called first because the schema slot may not
/// exist yet on the receiving replica — the snapshot is authoritative
/// for "what state exists for which target."
fn hydrate_schema_doc<C>(world: &mut World, target: CrdtId, path: Path, field: OpaqueValue)
where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    let mut doc = world.resource_mut::<SchemaDoc<C::Schema>>();
    doc.ensure_schema(target);
    if let Some(state) = doc.schema_mut(target) {
        if let Err(e) = state.install_state(&path, field) {
            tracing::warn!(?e, schema = %C::SCHEMA_NAME, "schema install_state failed");
        }
    }
}

// ---------------------------------------------------------------------------
// Generic pipeline systems — parameterized over `T: SchemaTarget`.
// ---------------------------------------------------------------------------

fn ensure_schema_slots<T, C>(
    mut doc: ResMut<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    has_c: Query<Entity, With<C>>,
) where
    T: SchemaTarget,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for entity in has_c.iter() {
        if let Some(id) = T::id_for(&index, entity) {
            doc.ensure_schema(id);
        }
    }
}

fn detect_typed_changes<T, C>(
    mut engine: ResMut<ClientSyncEngine>,
    doc: Res<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    components: Query<(Entity, Ref<C>), Changed<C>>,
) where
    T: SchemaTarget,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    // Lattice bottom for this schema. Cheap to construct once per
    // system run; used below to discriminate snapshot-hydration spawns
    // from genuine user mutations.
    let empty_schema = C::Schema::default();
    for (entity, component) in components.iter() {
        let Some(id) = T::id_for(&index, entity) else {
            continue;
        };
        let Some(current) = doc.schema(id) else {
            continue;
        };
        // Suppress the "reconnect clobber" failure mode: when a Welcome
        // snapshot arrives, `project_snapshot` spawns each node with
        // only the structural marker (e.g. `CircuitNode`), and on-add
        // observers (Mesh3d / Draggable3d / …) auto-insert
        // `Transform::default()` and other required components before
        // `project_typed_to_bevy` has a chance to write the hydrated
        // values back. Those default values trip `Changed<C>` and a
        // naive `changes_against` would emit ops setting every field
        // to its local default, broadcasting them to the room and
        // wiping out the canonical state held by other peers.
        //
        // The discriminator: snapshot-hydrated entities have
        // `component.is_added()` AND the doc already holds non-default
        // state (it was just installed by `hydrate_typed_schemas`).
        // User-spawned entities also have `is_added()` but the doc is
        // still at lattice bottom for that id, so they fall through to
        // the regular detect path and the initial values do replicate.
        if component.is_added() && *current != empty_schema {
            continue;
        }
        let mutations = component.changes_against(current);
        if mutations.is_empty() {
            continue;
        }
        let mut throwaway = current.clone();
        for mutation in mutations {
            let op_id = engine.mint_id();
            let mut state = kyoso_crdt::CausalState::new();
            let mut ctx = kyoso_crdt::CausalContext::new(op_id, None, &mut state);
            let typed_delta = throwaway.mutate(mutation, &mut ctx);
            let (inner_path, wire) = typed_delta.into_wire_op();
            let mut path = Path::field(C::SCHEMA_NAME);
            for seg in inner_path.0 {
                path.0.push(seg);
            }
            engine.enqueue(Op::new(op_id, T::build_op(id, path, wire)));
        }
    }
}

fn route_typed_inbound<T, C>(
    mut doc: ResMut<SchemaDoc<C::Schema>>,
    mut events: MessageReader<RemoteOpApplied>,
) where
    T: SchemaTarget,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for ev in events.read() {
        let op = &ev.0;
        let Some((target, path, delta)) = T::match_inbound(&op.kind) else {
            continue;
        };
        let Some(PathSegment::Field(head)) = path.0.first() else {
            continue;
        };
        if head != C::SCHEMA_NAME {
            continue;
        }
        let inner_path = Path(path.0[1..].to_vec());
        let stripped = Op {
            id: op.id,
            seq: op.seq,
            kind: T::build_op(target, inner_path, delta.clone()),
        };
        if let Err(e) = doc.apply_property_op(&stripped) {
            tracing::warn!(?e, schema = %C::SCHEMA_NAME, "schema apply rejected op");
        }
    }
}

fn project_typed_to_bevy<T, C>(
    mut commands: Commands,
    doc: Res<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    mut components: Query<&mut C>,
) where
    T: SchemaTarget,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    if !doc.is_changed() {
        return;
    }
    for (entity, id) in T::pairs(&index).iter() {
        let Some(schema) = doc.schema(*id) else { continue };
        match components.get_mut(*entity) {
            Ok(mut component) => component.write_back(schema),
            Err(_) => {
                let schema = schema.clone();
                commands.queue(InsertSchemaProjected::<C> {
                    entity: *entity,
                    schema,
                    _ph: PhantomData,
                });
            }
        }
    }
}

struct InsertSchemaProjected<C: SchemaSync> {
    entity: Entity,
    schema: C::Schema,
    _ph: PhantomData<fn() -> C>,
}

impl<C> Command for InsertSchemaProjected<C>
where
    C: SchemaSync,
{
    type Out = ();
    fn apply(self, world: &mut World) {
        let Ok(mut entity_mut) = world.get_entity_mut(self.entity) else {
            return;
        };
        if entity_mut.get::<C>().is_none() {
            entity_mut.insert(C::default());
        }
        if let Some(mut component) = entity_mut.get_mut::<C>() {
            component.write_back(&self.schema);
        }
    }
}

// ---------------------------------------------------------------------------
// Public plugins — thin specializations of the generic pipeline.
// ---------------------------------------------------------------------------

pub struct SchemaSyncedNodeComponentPlugin<N, E, C> {
    _phantom: PhantomData<fn() -> (N, E, C)>,
}

impl<N, E, C> Default for SchemaSyncedNodeComponentPlugin<N, E, C> {
    fn default() -> Self {
        Self {
            _phantom: PhantomData,
        }
    }
}

impl<N, E, C> Plugin for SchemaSyncedNodeComponentPlugin<N, E, C>
where
    N: Syncable,
    E: Syncable,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    fn build(&self, app: &mut App) {
        app.init_resource::<SchemaDoc<C::Schema>>();
        app.init_resource::<SchemaHydrators>();
        app.world_mut()
            .resource_mut::<SchemaHydrators>()
            .register::<NodeTarget, C>();
        app.add_systems(
            Update,
            (
                ensure_schema_slots::<NodeTarget, C>,
                detect_typed_changes::<NodeTarget, C>,
                route_typed_inbound::<NodeTarget, C>,
                project_typed_to_bevy::<NodeTarget, C>,
            )
                .chain()
                .after(crate::plugin::detect_added_nodes::<N, E>)
                .before(crate::plugin::outbound_system::<N, E>),
        );
    }
}

pub struct SchemaSyncedEdgeComponentPlugin<N, E, C> {
    _phantom: PhantomData<fn() -> (N, E, C)>,
}

impl<N, E, C> Default for SchemaSyncedEdgeComponentPlugin<N, E, C> {
    fn default() -> Self {
        Self {
            _phantom: PhantomData,
        }
    }
}

impl<N, E, C> Plugin for SchemaSyncedEdgeComponentPlugin<N, E, C>
where
    N: Syncable,
    E: Syncable,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    fn build(&self, app: &mut App) {
        app.init_resource::<SchemaDoc<C::Schema>>();
        app.init_resource::<SchemaHydrators>();
        app.world_mut()
            .resource_mut::<SchemaHydrators>()
            .register::<EdgeTarget, C>();
        app.add_systems(
            Update,
            (
                ensure_schema_slots::<EdgeTarget, C>,
                detect_typed_changes::<EdgeTarget, C>,
                route_typed_inbound::<EdgeTarget, C>,
                project_typed_to_bevy::<EdgeTarget, C>,
            )
                .chain()
                .after(crate::plugin::detect_added_edges::<N, E>)
                .before(crate::plugin::outbound_system::<N, E>),
        );
    }
}
