//! Typed-schema sync path for graph-model components.
//!
//! For each Bevy component `C` that implements [`SchemaSync`]:
//!
//! - A [`Document<C::Schema>`] resource holds the typed CRDT state for
//!   every node that carries `C`. Schema state is updated *only* by
//!   server-confirmed ops via [`Document::apply_property_op`].
//! - **Outbound**: `detect_typed_changes::<C>` runs whenever
//!   `Changed<C>` fires. It compares the Bevy component's current
//!   value against the document's known state via
//!   [`SchemaSync::changes_against`] and emits one wire op per changed
//!   field through the shared [`crate::ClientSyncEngine`].
//! - **Inbound**: `route_typed_inbound::<C>` reads the
//!   [`crate::RemoteOpApplied`] event stream, filters for ops whose
//!   `Path` head matches `C::SCHEMA_NAME`, strips that prefix, and
//!   routes the op to [`Document::apply_property_op`].
//! - **Projection**: `project_typed_to_bevy::<C>` watches the document
//!   for changes and writes the schema state back to the matching Bevy
//!   component via [`SchemaSync::write_back`].
//!
//! ## Wire-format namespacing
//!
//! `Path` is shared across all schemas, so each typed schema prefixes
//! its field paths with [`SchemaSync::SCHEMA_NAME`]:
//!
//! ```text
//! Set GraphNode.radius = 5.0  →  path = ["GraphNode", "radius"]
//! Set GraphEdge.line_width = 2  →  path = ["GraphEdge", "line_width"]
//! ```
//!
//! Inbound dispatch matches the head segment; the schema's own
//! `SchemaApply` impl (generated by `derive(Crdt)`) consumes the rest.

use std::marker::PhantomData;
use std::ops::{Deref, DerefMut};

use bevy::ecs::component::Mutable;
use bevy::prelude::*;
use kyoso_crdt::{Crdt, IntoWireOp, Op, Path, PathSegment, SchemaApply};
use kyoso_graph_crdt::{Document, OpKind};

use crate::engine::ClientSyncEngine;
use crate::index::EntityCrdtIndex;
use crate::plugin::{RemoteOpApplied, Syncable};

/// Bevy [`Resource`] wrapper around [`kyoso_graph_crdt::Document<S>`].
#[derive(Resource)]
pub struct SchemaDoc<S>(pub Document<S>)
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static;

impl<S> Default for SchemaDoc<S>
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static,
{
    fn default() -> Self {
        Self(Document::default())
    }
}

impl<S> Deref for SchemaDoc<S>
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static,
{
    type Target = Document<S>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<S> DerefMut for SchemaDoc<S>
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static,
{
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

/// Bridge between a Bevy component and a `derive(Crdt)` schema struct.
pub trait SchemaSync:
    Component<Mutability = Mutable> + Default + Sized + Send + Sync + 'static
{
    type Schema: Crdt + SchemaApply + Default + Clone + Send + Sync + 'static;
    const SCHEMA_NAME: &'static str;
    fn changes_against(&self, current: &Self::Schema) -> Vec<<Self::Schema as Crdt>::Mutation>;
    fn write_back(&mut self, schema: &Self::Schema);
}

/// Bridge for `#[crdt(with = "Type")]` schema fields — the escape hatch
/// for component fields whose Bevy type doesn't satisfy the standard
/// schema bounds (`Handle<Image>`, `Entity` references, opaque tokens
/// from external systems, types with custom serialization).
pub trait SchemaField: Crdt {
    type Component;
    fn changes_against(&self, component: &Self::Component) -> Vec<<Self as Crdt>::Mutation>;
    fn project_to(&self, component: &mut Self::Component);
}

impl<T> SchemaField for kyoso_crdt::types::LwwRegister<T>
where
    T: Clone
        + PartialEq
        + Default
        + serde::Serialize
        + for<'de> serde::Deserialize<'de>
        + Send
        + Sync
        + 'static,
{
    type Component = T;

    fn changes_against(&self, component: &Self::Component) -> Vec<<Self as Crdt>::Mutation> {
        let baseline = T::default();
        if self.get().unwrap_or(&baseline) != component {
            vec![kyoso_crdt::types::LwwMut::Set(component.clone())]
        } else {
            Vec::new()
        }
    }

    fn project_to(&self, component: &mut Self::Component) {
        if let Some(value) = self.get() {
            *component = value.clone();
        }
    }
}

pub struct SchemaSyncedNodeComponentPlugin<N, E, C> {
    _phantom: PhantomData<fn() -> (N, E, C)>,
}

impl<N, E, C> Default for SchemaSyncedNodeComponentPlugin<N, E, C> {
    fn default() -> Self {
        Self {
            _phantom: PhantomData,
        }
    }
}

impl<N, E, C> Plugin for SchemaSyncedNodeComponentPlugin<N, E, C>
where
    N: Syncable,
    E: Syncable,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    fn build(&self, app: &mut App) {
        app.init_resource::<SchemaDoc<C::Schema>>();
        app.add_systems(
            Update,
            (
                ensure_schema_slots::<C>,
                detect_typed_changes::<N, E, C>,
                route_typed_inbound::<C>,
                project_typed_to_bevy::<C>,
            )
                .chain()
                .after(crate::plugin::detect_added_nodes::<N, E>)
                .before(crate::plugin::outbound_system::<N, E>),
        );
    }
}

fn ensure_schema_slots<C>(
    mut doc: ResMut<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    has_c: Query<Entity, With<C>>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for entity in has_c.iter() {
        if let Some(id) = index.node_id(entity) {
            doc.ensure_node(id);
        }
    }
}

fn detect_typed_changes<N, E, C>(
    mut engine: ResMut<ClientSyncEngine>,
    doc: Res<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    components: Query<(Entity, Ref<C>), Changed<C>>,
) where
    N: Syncable,
    E: Syncable,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for (entity, component) in components.iter() {
        let Some(node_id) = index.node_id(entity) else {
            continue;
        };
        let Some(current) = doc.node(node_id) else {
            continue;
        };
        let mutations = component.changes_against(current);
        if mutations.is_empty() {
            continue;
        }
        let mut throwaway = current.clone();
        for mutation in mutations {
            let op_id = engine.next_id();
            let mut state = kyoso_crdt::CausalState::new();
            let mut ctx = kyoso_crdt::CausalContext::new(op_id, None, &mut state);
            let typed_delta = throwaway.mutate(mutation, &mut ctx);
            let (inner_path, wire) = typed_delta.into_wire_op();
            let mut path = Path::field(C::SCHEMA_NAME);
            for seg in inner_path.0 {
                path.0.push(seg);
            }
            engine.enqueue(Op::new(
                op_id,
                OpKind::SetNodeProperty {
                    target: node_id,
                    path,
                    delta: wire,
                },
            ));
        }
    }
}

fn route_typed_inbound<C>(
    mut doc: ResMut<SchemaDoc<C::Schema>>,
    mut events: MessageReader<RemoteOpApplied>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for ev in events.read() {
        let op = &ev.0;
        let OpKind::SetNodeProperty { target, path, delta } = &op.kind else {
            continue;
        };
        let Some(PathSegment::Field(head)) = path.0.first() else {
            continue;
        };
        if head != C::SCHEMA_NAME {
            continue;
        }
        let inner_path = Path(path.0[1..].to_vec());
        let stripped = Op {
            id: op.id,
            seq: op.seq,
            kind: OpKind::SetNodeProperty {
                target: *target,
                path: inner_path,
                delta: delta.clone(),
            },
        };
        if let Err(e) = doc.apply_property_op(&stripped) {
            tracing::warn!(?e, schema = %C::SCHEMA_NAME, "schema apply rejected op");
        }
    }
}

fn project_typed_to_bevy<C>(
    mut commands: Commands,
    doc: Res<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    mut components: Query<&mut C>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    if !doc.is_changed() {
        return;
    }
    for (entity, id) in index.node_of_entity.iter() {
        let Some(schema) = doc.node(*id) else { continue };
        match components.get_mut(*entity) {
            Ok(mut component) => component.write_back(schema),
            Err(_) => {
                let schema = schema.clone();
                commands.queue(InsertSchemaProjected::<C> {
                    entity: *entity,
                    schema,
                    _ph: PhantomData,
                });
            }
        }
    }
}

struct InsertSchemaProjected<C: SchemaSync> {
    entity: Entity,
    schema: C::Schema,
    _ph: PhantomData<fn() -> C>,
}

impl<C> Command for InsertSchemaProjected<C>
where
    C: SchemaSync,
{
    type Out = ();
    fn apply(self, world: &mut World) {
        let Ok(mut entity_mut) = world.get_entity_mut(self.entity) else {
            return;
        };
        if entity_mut.get::<C>().is_none() {
            entity_mut.insert(C::default());
        }
        if let Some(mut component) = entity_mut.get_mut::<C>() {
            component.write_back(&self.schema);
        }
    }
}

// ---------------------------------------------------------------------------
// Edge variant — mirrors the node plugin but works against
// `EntityCrdtIndex::edge_of_entity` and emits/routes
// `OpKind::SetRefEdgeProperty` ops.
// ---------------------------------------------------------------------------

pub struct SchemaSyncedEdgeComponentPlugin<N, E, C> {
    _phantom: PhantomData<fn() -> (N, E, C)>,
}

impl<N, E, C> Default for SchemaSyncedEdgeComponentPlugin<N, E, C> {
    fn default() -> Self {
        Self {
            _phantom: PhantomData,
        }
    }
}

impl<N, E, C> Plugin for SchemaSyncedEdgeComponentPlugin<N, E, C>
where
    N: Syncable,
    E: Syncable,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    fn build(&self, app: &mut App) {
        app.init_resource::<SchemaDoc<C::Schema>>();
        app.add_systems(
            Update,
            (
                ensure_edge_schema_slots::<C>,
                detect_typed_edge_changes::<N, E, C>,
                route_typed_edge_inbound::<C>,
                project_typed_edge_to_bevy::<C>,
            )
                .chain()
                .after(crate::plugin::detect_added_edges::<N, E>)
                .before(crate::plugin::outbound_system::<N, E>),
        );
    }
}

fn ensure_edge_schema_slots<C>(
    mut doc: ResMut<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    has_c: Query<Entity, With<C>>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for entity in has_c.iter() {
        if let Some(id) = index.edge_id(entity) {
            doc.ensure_node(id);
        }
    }
}

fn detect_typed_edge_changes<N, E, C>(
    mut engine: ResMut<ClientSyncEngine>,
    doc: Res<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    components: Query<(Entity, Ref<C>), Changed<C>>,
) where
    N: Syncable,
    E: Syncable,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for (entity, component) in components.iter() {
        let Some(edge_id) = index.edge_id(entity) else {
            continue;
        };
        let Some(current) = doc.node(edge_id) else {
            continue;
        };
        let mutations = component.changes_against(current);
        if mutations.is_empty() {
            continue;
        }
        let mut throwaway = current.clone();
        for mutation in mutations {
            let op_id = engine.next_id();
            let mut state = kyoso_crdt::CausalState::new();
            let mut ctx = kyoso_crdt::CausalContext::new(op_id, None, &mut state);
            let typed_delta = throwaway.mutate(mutation, &mut ctx);
            let (inner_path, wire) = typed_delta.into_wire_op();
            let mut path = Path::field(C::SCHEMA_NAME);
            for seg in inner_path.0 {
                path.0.push(seg);
            }
            engine.enqueue(Op::new(
                op_id,
                OpKind::SetRefEdgeProperty {
                    target: edge_id,
                    path,
                    delta: wire,
                },
            ));
        }
    }
}

fn route_typed_edge_inbound<C>(
    mut doc: ResMut<SchemaDoc<C::Schema>>,
    mut events: MessageReader<RemoteOpApplied>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for ev in events.read() {
        let op = &ev.0;
        let OpKind::SetRefEdgeProperty { target, path, delta } = &op.kind else {
            continue;
        };
        let Some(PathSegment::Field(head)) = path.0.first() else {
            continue;
        };
        if head != C::SCHEMA_NAME {
            continue;
        }
        let inner_path = Path(path.0[1..].to_vec());
        let stripped = Op {
            id: op.id,
            seq: op.seq,
            kind: OpKind::SetRefEdgeProperty {
                target: *target,
                path: inner_path,
                delta: delta.clone(),
            },
        };
        if let Err(e) = doc.apply_property_op(&stripped) {
            tracing::warn!(?e, schema = %C::SCHEMA_NAME, "edge schema apply rejected op");
        }
    }
}

fn project_typed_edge_to_bevy<C>(
    mut commands: Commands,
    doc: Res<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    mut components: Query<&mut C>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    if !doc.is_changed() {
        return;
    }
    for (entity, id) in index.edge_of_entity.iter() {
        let Some(schema) = doc.node(*id) else { continue };
        match components.get_mut(*entity) {
            Ok(mut component) => component.write_back(schema),
            Err(_) => {
                let schema = schema.clone();
                commands.queue(InsertSchemaProjected::<C> {
                    entity: *entity,
                    schema,
                    _ph: PhantomData,
                });
            }
        }
    }
}
