//! Typed-schema sync path: replaces the reflection-driven property
//! pipeline for components that opt into a [`SchemaSync`] schema.
//!
//! ## Architecture
//!
//! For each Bevy component `C` that implements [`SchemaSync`]:
//!
//! - A [`Document<C::Schema>`] resource holds the typed CRDT state for
//!   every node that carries `C`. Schema state is updated *only* by
//!   server-confirmed ops via [`Document::apply_property_op`].
//! - **Outbound**: `detect_typed_changes::<C>` runs whenever
//!   `Changed<C>` fires. It compares the Bevy component's current
//!   value against the document's known state via
//!   [`SchemaSync::changes_against`] and emits one wire op per changed
//!   field through the shared [`crate::ClientSyncEngine`].
//! - **Inbound**: `route_typed_inbound::<C>` reads the
//!   [`crate::RemoteOpApplied`] event stream, filters for ops whose
//!   `Path` head matches `C::SCHEMA_NAME`, strips that prefix, and
//!   routes the op to [`Document::apply_property_op`].
//! - **Projection**: `project_typed_to_bevy::<C>` watches the document
//!   for changes and writes the schema state back to the matching Bevy
//!   component via [`SchemaSync::write_back`].
//!
//! ## Wire-format namespacing
//!
//! `Path` is shared across all schemas, so each typed schema prefixes
//! its field paths with [`SchemaSync::SCHEMA_NAME`]:
//!
//! ```text
//! Set GraphNode.radius = 5.0  →  path = ["GraphNode", "radius"]
//! Set GraphEdge.line_width = 2  →  path = ["GraphEdge", "line_width"]
//! ```
//!
//! Inbound dispatch matches the head segment; the schema's own
//! `SchemaApply` impl (generated by `derive(Crdt)`) consumes the rest.

use std::marker::PhantomData;
use std::ops::{Deref, DerefMut};

use bevy::ecs::component::Mutable;
use bevy::prelude::*;
use kyoso_crdt::{Crdt, IntoWireOp, Op, Path, PathSegment, SchemaApply};
use kyoso_graph_crdt::{Document, OpKind};

use crate::plugin::{RemoteOpApplied, Syncable};
use crate::{ClientSyncEngine, EntityCrdtIndex};

/// Bevy [`Resource`] wrapper around [`kyoso_crdt::Document<S>`].
///
/// Necessary because both `Document<S>` (in `kyoso_crdt`) and
/// `Resource` (in `bevy`) are foreign types from this crate's
/// perspective — the orphan rule forbids `impl Resource for
/// Document<S>` here. The wrapper deref-passes through to the inner
/// document for ergonomics.
#[derive(Resource)]
pub struct SchemaDoc<S>(pub Document<S>)
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static;

impl<S> Default for SchemaDoc<S>
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static,
{
    fn default() -> Self {
        Self(Document::default())
    }
}

impl<S> Deref for SchemaDoc<S>
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static,
{
    type Target = Document<S>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<S> DerefMut for SchemaDoc<S>
where
    S: Crdt + SchemaApply + Default + Send + Sync + 'static,
    S::Delta: IntoWireOp,
    S::Mutation: Send + Sync + 'static,
{
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

/// Bridge between a Bevy component and a `derive(Crdt)` schema struct.
///
/// One impl per Bevy component you want to sync via the typed path.
/// Replaces the reflection-driven property serialization for that
/// component.
///
/// `Default` is required so the projection layer can insert a default
/// instance when a remote schema state arrives for an entity that
/// doesn't yet carry the component (`write_back` then mutates it into
/// the synced shape). The trait's idiomatic `changes_against` impl is
/// also expected to use `Self::default()` as the fallback baseline for
/// any field whose doc-state is bottom — see the doc-comment on
/// [`SchemaSync::changes_against`] for the convention.
pub trait SchemaSync:
    Component<Mutability = Mutable> + Default + Sized + Send + Sync + 'static
{
    /// The CRDT schema struct that mirrors `Self`'s synced fields.
    type Schema: Crdt + SchemaApply + Default + Clone + Send + Sync + 'static;

    /// Wire-format prefix for this schema. Every `Path` emitted by
    /// detection (and accepted by inbound routing) starts with this
    /// segment. Two schemas with the same `SCHEMA_NAME` would clash on
    /// the wire — make it unique per schema in your app.
    const SCHEMA_NAME: &'static str;

    /// Compute mutations that bring `current` (the document's last-
    /// applied state) into agreement with `self` (the Bevy component's
    /// current state). Each mutation in the returned vec becomes a
    /// `SetNodeProperty` op on the wire.
    ///
    /// **Echo-prevention convention**: compare each component field
    /// against `current.<field>.get().unwrap_or(&Self::default().<field>)`
    /// rather than `Some(&self.<field>)`. When the doc's field is
    /// bottom (no opinion yet — e.g. on a freshly inbound-spawned
    /// entity) this fallback compares against the component's *own*
    /// default value, so a `C::default()` instance produces zero
    /// mutations. Without this convention, fresh inbound-spawned
    /// components race the very `SetNodeProperty` ops they're echoing.
    ///
    /// ```ignore
    /// fn changes_against(&self, current: &Self::Schema)
    ///     -> Vec<<Self::Schema as Crdt>::Mutation>
    /// {
    ///     let default = Self::default();
    ///     let mut out = Vec::new();
    ///     if *current.radius.get().unwrap_or(&default.radius) != self.radius {
    ///         out.push(SchemaMut::Radius(LwwMut::Set(self.radius)));
    ///     }
    ///     out
    /// }
    /// ```
    fn changes_against(
        &self,
        current: &Self::Schema,
    ) -> Vec<<Self::Schema as Crdt>::Mutation>;

    /// Update `self` so its synced fields match `schema`. Called by
    /// `project_typed_to_bevy` whenever the document state changes.
    fn write_back(&mut self, schema: &Self::Schema);
}

/// Bridge for `#[crdt(with = "Type")]` schema fields — the escape hatch
/// for component fields whose Bevy type doesn't satisfy the standard
/// schema bounds (`Handle<Image>`, `Entity` references, opaque tokens
/// from external systems, types with custom serialization).
///
/// An implementor is a typed CRDT struct that knows how to project to
/// and from a specific Bevy-side component field type.
///
/// ## Required impls
///
/// A `with`-type must implement:
/// - [`Crdt`] + [`SchemaApply`] + [`crate::schema_sync::SchemaField`]
///   (this trait).
/// - `Default + Clone + Debug + PartialEq` (for the outer schema's
///   derived traits via `derive(Crdt)`).
/// - `<Self as Crdt>::Delta: IntoWireOp + From<WireDelta> +
///   TryFrom<WireDelta>` (for wire conversion in either direction).
///
/// In practice, easiest path: hand-roll a small struct that wraps an
/// existing CRDT primitive (e.g. `LwwRegister<T>`) and impls `Crdt` by
/// delegation, then add `SchemaField` with custom `changes_against` /
/// `project_to`.
///
/// ## Built-in impls
///
/// `LwwRegister<T>` implements `SchemaField` directly with `Component =
/// T` (LWW echo-guard against `T::default()`). This means
/// `#[crdt(with = "LwwRegister<T>")]` is functionally equivalent to
/// `#[crdt(lww)]` and can serve as a worked example.
pub trait SchemaField: Crdt {
    /// The component-side field type this schema-field projects.
    type Component;

    /// Compute mutations that bring `component` (the local Bevy field
    /// value) into agreement with `self` (the doc-side schema state).
    /// Each emitted mutation becomes one `<OuterSchemaMut>::<Variant>`
    /// payload on the wire.
    fn changes_against(
        &self,
        component: &Self::Component,
    ) -> Vec<<Self as Crdt>::Mutation>;

    /// Project the schema state onto the component field.
    fn project_to(&self, component: &mut Self::Component);
}

impl<T> SchemaField for kyoso_crdt::types::LwwRegister<T>
where
    T: Clone
        + PartialEq
        + Default
        + serde::Serialize
        + for<'de> serde::Deserialize<'de>
        + Send
        + Sync
        + 'static,
{
    type Component = T;

    fn changes_against(
        &self,
        component: &Self::Component,
    ) -> Vec<<Self as Crdt>::Mutation> {
        let baseline = T::default();
        if self.get().unwrap_or(&baseline) != component {
            vec![kyoso_crdt::types::LwwMut::Set(component.clone())]
        } else {
            Vec::new()
        }
    }

    fn project_to(&self, component: &mut Self::Component) {
        if let Some(value) = self.get() {
            *component = value.clone();
        }
    }
}

/// Plugin that wires a typed `SchemaSync` component into the sync
/// layer. Add one per component type you want synced via the typed
/// (non-reflection) path.
///
/// ```ignore
/// app.add_plugins(SchemaSyncedNodeComponentPlugin::<N, E, GraphNode>::default());
/// ```
pub struct SchemaSyncedNodeComponentPlugin<N, E, C> {
    _phantom: PhantomData<fn() -> (N, E, C)>,
}

impl<N, E, C> Default for SchemaSyncedNodeComponentPlugin<N, E, C> {
    fn default() -> Self {
        Self {
            _phantom: PhantomData,
        }
    }
}

impl<N, E, C> Plugin for SchemaSyncedNodeComponentPlugin<N, E, C>
where
    N: Syncable,
    E: Syncable,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    fn build(&self, app: &mut App) {
        app.init_resource::<SchemaDoc<C::Schema>>();
        // Order matters:
        //   - `ensure_schema_slots` first so every node has a doc slot.
        //   - `detect_typed_changes` next, BEFORE inbound apply +
        //     projection. This captures the user's local edit (Bevy
        //     `Changed<C>`) before projection might overwrite it with
        //     a stale doc value (e.g. a loopback for an earlier user
        //     edit landing in the same frame as a fresh user edit).
        //     Detection's own echo guard skips emissions where
        //     `Added<C>` AND `component == C::default()` — that's the
        //     inbound projector's transient default-spawn, not a real
        //     user mutation.
        //   - `route_typed_inbound` then `project_typed_to_bevy` apply
        //     server-confirmed updates to doc + Bevy components.
        //   - Whole chain after `detect_added_nodes` (entity is bound)
        //     and before `outbound_system` (ops ship the same frame).
        app.add_systems(
            Update,
            (
                ensure_schema_slots::<C>,
                detect_typed_changes::<N, E, C>,
                route_typed_inbound::<C>,
                project_typed_to_bevy::<C>,
            )
                .chain()
                .after(crate::plugin::detect_added_nodes::<N, E>)
                .before(crate::plugin::outbound_system::<N, E>),
        );
    }
}

/// Ensure node entities that locally carry `C` have a corresponding
/// schema slot in the document. Filtered by `With<C>` so multi-component
/// apps (e.g. one in which Frame, Rectangle, and Text are distinct node
/// kinds) don't pollute every schema's doc with default-valued slots
/// for every entity. Inbound apply auto-creates slots in
/// [`Document::apply_property_op`] for entities that didn't have `C`
/// locally yet — projection then inserts `C::default()` and writes back.
fn ensure_schema_slots<C>(
    mut doc: ResMut<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    has_c: Query<Entity, With<C>>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for entity in has_c.iter() {
        if let Some(id) = index.node_id(entity) {
            doc.ensure_node(id);
        }
    }
}

/// Outbound: detect Bevy `Changed<C>` and emit typed wire ops.
fn detect_typed_changes<N, E, C>(
    mut engine: ResMut<ClientSyncEngine>,
    doc: Res<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    components: Query<(Entity, Ref<C>), Changed<C>>,
) where
    N: Syncable,
    E: Syncable,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for (entity, component) in components.iter() {
        let Some(node_id) = index.node_id(entity) else {
            continue;
        };
        let Some(current) = doc.node(node_id) else {
            continue;
        };
        let mutations = component.changes_against(current);
        if mutations.is_empty() {
            continue;
        }
        // Apply mutations to a throwaway clone of `current` so we can
        // compute each typed delta in turn. This keeps `Document<S>`
        // free of any locally-pre-applied state — visibility waits
        // for the server roundtrip via `route_typed_inbound`.
        let mut throwaway = current.clone();
        for mutation in mutations {
            let op_id = engine.next_id();
            let mut state = kyoso_crdt::CausalState::new();
            let mut ctx = kyoso_crdt::CausalContext::new(op_id, None, &mut state);
            let typed_delta = throwaway.mutate(mutation, &mut ctx);
            let (inner_path, wire) = typed_delta.into_wire_op();
            // Prepend the schema discriminator so inbound routing on
            // remote peers can match against C::SCHEMA_NAME.
            let mut path = Path::field(C::SCHEMA_NAME);
            for seg in inner_path.0 {
                path.0.push(seg);
            }
            engine.enqueue(Op::new(
                op_id,
                OpKind::SetNodeProperty {
                    target: node_id,
                    path,
                    delta: wire,
                },
            ));
        }
    }
}

/// Inbound: read every `RemoteOpApplied`, filter by schema discriminator,
/// route to `Document<C::Schema>`. Strips the discriminator from the
/// path before passing to the schema's `SchemaApply`.
fn route_typed_inbound<C>(
    mut doc: ResMut<SchemaDoc<C::Schema>>,
    mut events: MessageReader<RemoteOpApplied>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for ev in events.read() {
        let op = &ev.0;
        let OpKind::SetNodeProperty { target, path, delta } = &op.kind else {
            continue;
        };
        // First segment must match this schema's discriminator.
        let Some(PathSegment::Field(head)) = path.0.first() else {
            continue;
        };
        if head != C::SCHEMA_NAME {
            continue;
        }
        // Build a stripped op: same target/seq/id but path without the
        // schema-name prefix. The schema's `apply_wire` consumes the
        // remaining segments.
        let inner_path = Path(path.0[1..].to_vec());
        let stripped = Op {
            id: op.id,
            seq: op.seq,
            kind: OpKind::SetNodeProperty {
                target: *target,
                path: inner_path,
                delta: delta.clone(),
            },
        };
        if let Err(e) = doc.apply_property_op(&stripped) {
            tracing::warn!(?e, schema = %C::SCHEMA_NAME, "schema apply rejected op");
        }
    }
}

/// Projection: write document schema state back to the matching Bevy
/// component whenever the document changes. Inserts a default `C` if
/// the entity doesn't yet carry one (parity with the reflection path,
/// which auto-inserted on first remote SetNodeProperty).
fn project_typed_to_bevy<C>(
    mut commands: Commands,
    doc: Res<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    mut components: Query<&mut C>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    if !doc.is_changed() {
        return;
    }
    for (entity, id) in index.node_of_entity.iter() {
        let Some(schema) = doc.node(*id) else { continue };
        match components.get_mut(*entity) {
            Ok(mut component) => component.write_back(schema),
            Err(_) => {
                let schema = schema.clone();
                commands.queue(InsertSchemaProjected::<C> {
                    entity: *entity,
                    schema,
                    _ph: PhantomData,
                });
            }
        }
    }
}

/// Deferred insert: spawn a default `C` on the entity, then `write_back`
/// the captured schema state.
struct InsertSchemaProjected<C: SchemaSync> {
    entity: Entity,
    schema: C::Schema,
    _ph: PhantomData<fn() -> C>,
}

impl<C> Command for InsertSchemaProjected<C>
where
    C: SchemaSync,
{
    type Out = ();
    fn apply(self, world: &mut World) {
        let Ok(mut entity_mut) = world.get_entity_mut(self.entity) else {
            return;
        };
        if entity_mut.get::<C>().is_none() {
            entity_mut.insert(C::default());
        }
        if let Some(mut component) = entity_mut.get_mut::<C>() {
            component.write_back(&self.schema);
        }
    }
}

// ---------------------------------------------------------------------------
// Edge variant — mirrors the node plugin but works against
// `EntityCrdtIndex::edge_of_entity` and emits/routes
// `OpKind::SetRefEdgeProperty` ops.
// ---------------------------------------------------------------------------

/// Edge-side counterpart to [`SchemaSyncedNodeComponentPlugin`]. Add
/// one per edge component that should sync via a typed schema.
///
/// ```ignore
/// app.add_plugins(SchemaSyncedEdgeComponentPlugin::<N, E, GraphEdge>::default());
/// ```
pub struct SchemaSyncedEdgeComponentPlugin<N, E, C> {
    _phantom: PhantomData<fn() -> (N, E, C)>,
}

impl<N, E, C> Default for SchemaSyncedEdgeComponentPlugin<N, E, C> {
    fn default() -> Self {
        Self {
            _phantom: PhantomData,
        }
    }
}

impl<N, E, C> Plugin for SchemaSyncedEdgeComponentPlugin<N, E, C>
where
    N: Syncable,
    E: Syncable,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    fn build(&self, app: &mut App) {
        app.init_resource::<SchemaDoc<C::Schema>>();
        // Same ordering rationale as the node plugin: detect first
        // (capture user edits before inbound apply / projection might
        // overwrite them); detect's echo guard skips just-added default
        // components. Then apply inbound + project doc → component.
        app.add_systems(
            Update,
            (
                ensure_edge_schema_slots::<C>,
                detect_typed_edge_changes::<N, E, C>,
                route_typed_edge_inbound::<C>,
                project_typed_edge_to_bevy::<C>,
            )
                .chain()
                .after(crate::plugin::detect_added_edges::<N, E>)
                .before(crate::plugin::outbound_system::<N, E>),
        );
    }
}

fn ensure_edge_schema_slots<C>(
    mut doc: ResMut<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    has_c: Query<Entity, With<C>>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    // Same rationale as `ensure_schema_slots` — see its docstring.
    for entity in has_c.iter() {
        if let Some(id) = index.edge_id(entity) {
            doc.ensure_node(id);
        }
    }
}

fn detect_typed_edge_changes<N, E, C>(
    mut engine: ResMut<ClientSyncEngine>,
    doc: Res<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    components: Query<(Entity, Ref<C>), Changed<C>>,
) where
    N: Syncable,
    E: Syncable,
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for (entity, component) in components.iter() {
        let Some(edge_id) = index.edge_id(entity) else {
            continue;
        };
        let Some(current) = doc.node(edge_id) else {
            continue;
        };
        let mutations = component.changes_against(current);
        if mutations.is_empty() {
            continue;
        }
        let mut throwaway = current.clone();
        for mutation in mutations {
            let op_id = engine.next_id();
            let mut state = kyoso_crdt::CausalState::new();
            let mut ctx = kyoso_crdt::CausalContext::new(op_id, None, &mut state);
            let typed_delta = throwaway.mutate(mutation, &mut ctx);
            let (inner_path, wire) = typed_delta.into_wire_op();
            let mut path = Path::field(C::SCHEMA_NAME);
            for seg in inner_path.0 {
                path.0.push(seg);
            }
            engine.enqueue(Op::new(
                op_id,
                OpKind::SetRefEdgeProperty {
                    target: edge_id,
                    path,
                    delta: wire,
                },
            ));
        }
    }
}

fn route_typed_edge_inbound<C>(
    mut doc: ResMut<SchemaDoc<C::Schema>>,
    mut events: MessageReader<RemoteOpApplied>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    for ev in events.read() {
        let op = &ev.0;
        let OpKind::SetRefEdgeProperty { target, path, delta } = &op.kind else {
            continue;
        };
        let Some(PathSegment::Field(head)) = path.0.first() else {
            continue;
        };
        if head != C::SCHEMA_NAME {
            continue;
        }
        let inner_path = Path(path.0[1..].to_vec());
        let stripped = Op {
            id: op.id,
            seq: op.seq,
            kind: OpKind::SetRefEdgeProperty {
                target: *target,
                path: inner_path,
                delta: delta.clone(),
            },
        };
        if let Err(e) = doc.apply_property_op(&stripped) {
            tracing::warn!(?e, schema = %C::SCHEMA_NAME, "edge schema apply rejected op");
        }
    }
}

fn project_typed_edge_to_bevy<C>(
    mut commands: Commands,
    doc: Res<SchemaDoc<C::Schema>>,
    index: Res<EntityCrdtIndex>,
    mut components: Query<&mut C>,
) where
    C: SchemaSync,
    <C::Schema as Crdt>::Delta: IntoWireOp,
    <C::Schema as Crdt>::Mutation: Send + Sync + 'static,
{
    if !doc.is_changed() {
        return;
    }
    for (entity, id) in index.edge_of_entity.iter() {
        let Some(schema) = doc.node(*id) else { continue };
        match components.get_mut(*entity) {
            Ok(mut component) => component.write_back(schema),
            Err(_) => {
                let schema = schema.clone();
                commands.queue(InsertSchemaProjected::<C> {
                    entity: *entity,
                    schema,
                    _ph: PhantomData,
                });
            }
        }
    }
}
