//! `#[derive(Crdt)]` for kyoso schema structs.
//!
//! Given a struct of CRDT-typed fields:
//!
//! ```ignore
//! #[derive(Crdt)]
//! pub struct NodeProperties {
//!     pub name: LwwRegister<String>,
//!     pub tags: OrSet<String>,
//!     pub counter: PnCounter,
//! }
//! ```
//!
//! the macro generates:
//!
//! - `NodePropertiesMut` — a sum type with one variant per field carrying
//!   that field's `Crdt::Mutation`.
//! - `NodePropertiesDelta` — same shape over `Crdt::Delta`.
//! - `impl Lattice for NodeProperties` — pointwise join.
//! - `impl Crdt for NodeProperties` — typed apply / mutate.
//! - `impl SchemaApply for NodeProperties` — wire-driven dispatch on
//!   `Path` head field name.
//!
//! Each field type must implement [`kyoso_crdt::Crdt`] and its `Delta`
//! must convert to/from [`kyoso_crdt::WireDelta`] (`From` + `TryFrom`
//! with `Error = DeltaError`).

use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Fields, Ident, parse_macro_input};

#[proc_macro_derive(Crdt)]
pub fn derive_crdt(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;
    let mutation_name = format_ident!("{}Mut", name);
    let delta_name = format_ident!("{}Delta", name);

    let fields = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(named) => &named.named,
            _ => {
                return syn::Error::new(
                    Span::call_site(),
                    "Crdt derive requires a struct with named fields",
                )
                .to_compile_error()
                .into();
            }
        },
        _ => {
            return syn::Error::new(
                Span::call_site(),
                "Crdt derive requires a struct (not enum or union)",
            )
            .to_compile_error()
            .into();
        }
    };

    let field_idents: Vec<&Ident> = fields.iter().map(|f| f.ident.as_ref().unwrap()).collect();
    let field_types: Vec<&syn::Type> = fields.iter().map(|f| &f.ty).collect();
    let field_strs: Vec<String> = field_idents.iter().map(ToString::to_string).collect();
    let variant_idents: Vec<Ident> = field_idents
        .iter()
        .map(|i| format_ident!("{}", to_pascal_case(&i.to_string())))
        .collect();

    let expanded = quote! {
        /// Generated by `#[derive(Crdt)]`. One variant per schema field.
        #[derive(Clone, Debug, PartialEq)]
        #[allow(clippy::pub_enum_variant_names, dead_code)]
        pub enum #mutation_name {
            #( #variant_idents(<#field_types as ::kyoso_crdt::Crdt>::Mutation), )*
        }

        /// Generated by `#[derive(Crdt)]`. Typed delta, sum over fields.
        #[derive(Clone, Debug, PartialEq)]
        #[allow(clippy::pub_enum_variant_names, dead_code)]
        pub enum #delta_name {
            #( #variant_idents(<#field_types as ::kyoso_crdt::Crdt>::Delta), )*
        }

        impl ::kyoso_crdt::Lattice for #name {
            fn bottom() -> Self {
                Self {
                    #( #field_idents: <#field_types as ::kyoso_crdt::Lattice>::bottom(), )*
                }
            }

            fn join(&mut self, other: Self) {
                #( ::kyoso_crdt::Lattice::join(&mut self.#field_idents, other.#field_idents); )*
            }
        }

        impl ::kyoso_crdt::Crdt for #name {
            type Mutation = #mutation_name;
            type Delta = #delta_name;

            fn apply(
                &mut self,
                delta: &Self::Delta,
                ctx: &::kyoso_crdt::CausalContext,
            ) -> ::core::result::Result<(), ::kyoso_crdt::DeltaError> {
                match delta {
                    #(
                        #delta_name::#variant_idents(d) =>
                            ::kyoso_crdt::Crdt::apply(&mut self.#field_idents, d, ctx),
                    )*
                }
            }

            fn mutate(
                &mut self,
                m: Self::Mutation,
                ctx: &mut ::kyoso_crdt::CausalContext,
            ) -> Self::Delta {
                match m {
                    #(
                        #mutation_name::#variant_idents(m) =>
                            #delta_name::#variant_idents(
                                ::kyoso_crdt::Crdt::mutate(&mut self.#field_idents, m, ctx)
                            ),
                    )*
                }
            }
        }

        impl ::kyoso_crdt::SchemaApply for #name {
            fn apply_wire(
                &mut self,
                path: &::kyoso_crdt::Path,
                delta: ::kyoso_crdt::WireDelta,
                ctx: &::kyoso_crdt::CausalContext,
            ) -> ::core::result::Result<(), ::kyoso_crdt::DeltaError> {
                let (head, tail) = ::kyoso_crdt::schema::split_field_head(path)?;
                match head {
                    #(
                        #field_strs => {
                            // Recurse: the field's own SchemaApply impl
                            // either consumes the empty tail (leaf
                            // CRDTs like LwwRegister) or walks further
                            // (nested struct, CausalMap).
                            ::kyoso_crdt::SchemaApply::apply_wire(
                                &mut self.#field_idents,
                                &tail,
                                delta,
                                ctx,
                            )
                        }
                    )*
                    other => ::core::result::Result::Err(
                        ::kyoso_crdt::DeltaError::UnknownPath {
                            segment: other.to_string(),
                        },
                    ),
                }
            }

            fn install_state(
                &mut self,
                path: &::kyoso_crdt::Path,
                field: ::kyoso_crdt::OpaqueField,
            ) -> ::core::result::Result<(), ::kyoso_crdt::DeltaError> {
                // Same dispatch shape as `apply_wire`: walk the head
                // segment to the matching field and recurse. Leaf
                // primitives consume the empty tail; nested schemas /
                // maps walk further.
                let (head, tail) = ::kyoso_crdt::schema::split_field_head(path)?;
                match head {
                    #(
                        #field_strs => {
                            ::kyoso_crdt::SchemaApply::install_state(
                                &mut self.#field_idents,
                                &tail,
                                field,
                            )
                        }
                    )*
                    other => ::core::result::Result::Err(
                        ::kyoso_crdt::DeltaError::UnknownPath {
                            segment: other.to_string(),
                        },
                    ),
                }
            }
        }

        impl ::kyoso_crdt::IntoWireOp for #delta_name {
            fn into_wire_op(self) -> (::kyoso_crdt::Path, ::kyoso_crdt::WireDelta) {
                match self {
                    #(
                        #delta_name::#variant_idents(d) => {
                            // Recurse: leaf Deltas (`LwwDelta`, `OrSetDelta`,
                            // ...) return `(Path::new(), wire)`; nested
                            // schema Deltas return their own multi-segment
                            // path. Either way we prepend our field name.
                            let (inner, wire) = ::kyoso_crdt::IntoWireOp::into_wire_op(d);
                            let mut path = ::kyoso_crdt::Path::field(#field_strs);
                            for seg in inner.0 {
                                path.0.push(seg);
                            }
                            (path, wire)
                        },
                    )*
                }
            }
        }
    };

    TokenStream::from(expanded)
}

/// Convert `snake_case` to `PascalCase`. Used to derive enum variant
/// names from field idents.
fn to_pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut next_upper = true;
    for ch in s.chars() {
        if ch == '_' {
            next_upper = true;
        } else if next_upper {
            out.extend(ch.to_uppercase());
            next_upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}
