//! Bevy-native, opinionated Figma-shaped document model — the core
//! crate.
//!
//! This crate **defines components and the document taxonomy**.
//! It is intentionally domain-agnostic about *where* a scene came from
//! — Figma import, hand-authored, generated by an agent, or
//! procedurally — and serves as the test substrate for the
//! `kyoso_graph` infrastructure.
//!
//! For the Figma REST-API → ECS import adapter, see the sibling
//! `kyoso_figma` crate.
//!
//! ## What this crate provides
//!
//! - **Component definitions** — `Frame`, `Rectangle`, `Text` and their
//!   value-type satellites `Size`, `Paint`, `TypeStyle`. Each is a Bevy
//!   `Component` with `derive(SchemaSync)` so per-field mutations
//!   replicate via the `kyoso_sync` typed schema path. CRDT-kind choice
//!   per field (LWW for scalars, OrSet for fills, Sequence for collab
//!   text, nested for TypeStyle inside Text).
//! - **Structural markers** — `SceneNode` and `SceneEdge` (zero-sized
//!   types) used as the `<N, E>` parameters to
//!   [`kyoso_graph_sync::GraphSyncPlugin`]. Every spawned scene entity
//!   carries `SceneNode` plus exactly one of the field-bearing components.
//! - **`KyosoCorePlugin`** — single-call entry point that registers
//!   all per-component schema plugins.
//!
//! ## Opinionated departures from Figma's data model
//!
//! - **Group + Frame unified** as `Frame` with a `clips_content: bool`.
//! - **No `absolute_bounding_box`** — position+rotation+scale via
//!   Bevy `Transform`; size via the standalone `Size` component.
//!   World coords come from `GlobalTransform` on demand.
//! - **Idiomatic Rust field names** — snake_case; `is_clip` →
//!   `clips_content`; etc.
//!
//! ## Initial cut scope
//!
//! Three node types: `Frame`, `Rectangle`, `Text`. `Page` /
//! `Component` / `Instance` / `Vector` / `Group` / `BooleanOperation`
//! and the rest of Figma's surface are deferred.

use bevy::prelude::*;
use serde::{Deserialize, Serialize};

pub mod descriptor;
pub mod frame;
pub mod node;
pub mod paint;
pub mod plugin;
pub mod query_data;
pub mod rectangle;
pub mod scene_world;
pub mod size;
pub mod text;
pub mod typestyle;

pub use descriptor::{node_payload, node_type_str, scene_node_descriptor};
pub use frame::{Frame, FrameData, FrameQueryData, LayoutMode};
pub use node::Node;
// NodeVariant / EdgeVariant are the per-variant relator traits; re-exported
// from `kyoso_graph` (they live there because they're graph-crate concerns).
pub use kyoso_graph::{EdgeVariant, NodeVariant};
pub use paint::{GradientStop, GradientType, ImageScaleMode, Paint};
pub use plugin::KyosoCorePlugin;
pub use query_data::AnyNodeQueryData;
pub use rectangle::{Rectangle, RectangleData, RectangleQueryData};
pub use scene_world::SceneWorld;
pub use size::Size;
pub use text::{Text, TextData, TextQueryData};
pub use typestyle::TypeStyle;

/// Domain-typed [`kyoso_graph::scene::Scene`] for the kyoso_core
/// scene model:
/// `Scene<&SceneNode, &SceneEdge, With<SceneNode>>`.
///
/// Convenience alias for in-system reads that want both the scene
/// hierarchy and the entity-edge graph **filtered to entities
/// carrying the [`SceneNode`] marker**. The `With<SceneNode>` filter
/// is shared by both inner queries — non-`SceneNode` overlays are
/// invisible to both `scene.tree.*` and `scene.graph.*`. Use the
/// agent-facing [`kyoso_graph::traversal::WorldGraphView`] (or
/// [`SceneWorld`]) if you need to see bare overlays too.
pub type SceneView<'w, 's> = kyoso_graph::scene::Scene<
    'w,
    's,
    &'static SceneNode,
    &'static SceneEdge,
    bevy::ecs::query::With<SceneNode>,
>;

// ---------------------------------------------------------------------------
// Structural markers
// ---------------------------------------------------------------------------

/// Zero-sized marker: every kyoso_core node entity carries this. Used
/// as the `N` parameter to [`kyoso_graph_sync::GraphSyncPlugin`] so
/// structural ops (`AddNode`, `RemoveNode`, `Move`) operate on a
/// uniform "this is a scene node" identity, decoupled from which
/// specific node kind (`Frame` / `Rectangle` / `Text` / ...) the
/// entity carries.
#[derive(Component, Default, Clone, Debug, PartialEq, Eq, Reflect)]
#[reflect(Component, Default)]
#[require(kyoso_graph_sync::NodePresence)]
pub struct SceneNode;

/// Discriminator tag: which variant of [`Node`](crate::node::Node) does
/// this entity carry? Inserted atomically with the variant's data via
/// the `*Data` bundles (see [`FrameData`](crate::FrameData) etc.)
/// so the tag and the data cannot drift apart.
#[derive(
    Component, Reflect, Copy, Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize,
    schemars::JsonSchema,
)]
#[reflect(Component)]
#[serde(rename_all = "snake_case")]
pub enum NodeKind {
    Frame,
    Rectangle,
    Text,
}

/// Zero-sized marker: every kyoso_core edge entity carries this. The
/// initial cut only uses tree edges (via `kyoso_graph::tree`);
/// reference edges (component→main, prototype links) are deferred.
#[derive(Component, Default, Clone, Debug, PartialEq, Eq, Reflect)]
#[reflect(Component, Default)]
#[require(kyoso_graph_sync::EdgeEndpoints)]
pub struct SceneEdge;

// ---------------------------------------------------------------------------
// Typed-graph trait impl — SceneNode IS the typed graph identifier.
// One `impl Graph for SceneNode` replaces the previous separate
// `TypedGraphNode` + `TypedGraphEdge` impls.
// ---------------------------------------------------------------------------

impl kyoso_graph::Graph for SceneNode {
    // Nodes
    type NodeMarker = SceneNode;
    type Node = crate::node::Node;
    type NodeData = crate::query_data::AnyNodeQueryData;
    type NodeDiscriminator = NodeKind;
    /// The closed family of scene-node variants, in dispatch order.
    /// The `NodeVariants` tuple impl (arity 3) drives
    /// `try_materialize(Entity → Node)` over `&World` directly — used
    /// by the agent-facing traversal layer in `crate::traversal`.
    /// Adding a fourth kind = a new `NodeVariant` impl + one entry here.
    type Variants = (Frame, Rectangle, Text);
    // Edges — no typed edges yet; `()` is the empty-edge-variant shape.
    type EdgeMarker = SceneEdge;
    type Edge = ();
    type EdgeData = ();
    type EdgeDiscriminator = ();
}
